CREATE TABLE servicios( 
SERVICIOSID INT,
AGUA NUMBER(1,0) NOT NULL,
BAÑERA NUMBER(1,0) NOT NULL,
COCINETA NUMBER(1,0) NOT NULL,
PARQUEADERO NUMBER(1,0) NOT NULL,
PISCINA NUMBER(1,0) NOT NULL,
RECEPCION24H NUMBER(1,0) NOT NULL,
RESTAURANTE NUMBER(1,0) NOT NULL,
SALA NUMBER(1,0) NOT NULL,
TV NUMBER(1,0) NOT NULL,
WIFI NUMBER(1,0) NOT NULL,
YACUZZI NUMBER(1,0) NOT NULL,
HABITACIONID INT NOT NULL,
PRIMARY KEY (SERVICIOSID)
);

CREATE TABLE HABITACION(
COMPARTIDA NUMBER(1,0) NOT NULL,
DESCRIPCION VARCHAR2(100) NOT NULL,
OCUPADA NUMBER(1,0) NOT NULL,
HABITACIONID INT NOT NULL,
RESERVA INT,
HOTELERIAID INT,
COMUNIDADID INT,
RESERVAID INT,
PRIMARY KEY (HABITACIONID)
);

CREATE TABLE HOTELERIA(
NOMBRE VARCHAR2(100) NOT NULL,
CAPACIDAD INT NOT NULL,
DISPONIBILIDAD INT NOT NULL,
REGISTROCAMARACOMERCIO VARCHAR2(100) NOT NULL,
REGISTROSUPERINTENDENCIA VARCHAR2(100) NOT NULL, 
UBICACION VARCHAR2(100) NOT NULL,
HOTELERIAID INT NOT NULL,
COMUNIDADID INT,
TIPOH VARCHAR2(100) NOT NULL,
HORAAPERTURA VARCHAR2(100),
HORACIERRE VARCHAR2(100),
PRIMARY KEY (HOTELERIAID),
CONSTRAINT chk_TIPOH CHECK (TIPOH IN ('HOSTAL', 'HOTEL'))
);

CREATE TABLE RESERVA(
FECHAFINAL VARCHAR2(100),
FECHAINICIAL VARCHAR2(100),
PRECIO INT,
MENAJE  NUMBER(1,0),
NUMEROHABITACIONES INT,
INCLUYEADMIN NUMBER(1,0),
INCLUYESERVPUBLICOS  NUMBER(1,0),
PRECIOSERVPUBLICOS  NUMBER(1,0),
ACCESOCOCINA NUMBER(1,0),
BAÑOPRIVADO VARCHAR2(100),
COMIDAS NUMBER(1,0),
DURACION INT,
HABITACIONINDIVIDUAL NUMBER(1,0),
PRECIOSERVICIOS INT,
RESERVAID INT,
COMUNIDADID INT NOT NULL,
TIPOR VARCHAR2(100) NOT NULL,
PRIMARY KEY (RESERVAID),
CONSTRAINT chk_TIPOR CHECK (TIPOR IN ('CONTRATOAPARTAMENTO', 'CONTRATOVIVIENDA', 'CONTRATOHABITACION'))
);

CREATE TABLE COMUNIDAD(
CARNET INT NOT NULL,
NOMBRE VARCHAR2(100) NOT NULL,
ROL VARCHAR2(100) NOT NULL,
COMUNIDADID INT,
TIPO VARCHAR2(100) NOT NULL, 
RESERVAACTUAL INT,
PRIMARY KEY (COMUNIDADID),
CONSTRAINT chk_TIPO CHECK (TIPO IN ('CLIENTE', 'OPERADOR'))
);

CREATE TABLE SEGURO (
COSTO INT NOT NULL,
VIGENCIA  NUMBER(1,0) NOT NULL,
SEGUROID INT NOT NULL,
RESERVAID INT NOT NULL,
PRIMARY KEY (SEGUROID)
);

CREATE TABLE VIVIENDA (
MENAJE NUMBER(1,0) NOT NULL,
NUMEROHABITACIONES INT NOT NULL,
OCUPADA NUMBER(1,0) NOT NULL, 
UBICACION VARCHAR2(100) NOT NULL,
VIVIENDAID INT, 
COMUNIDADID INT NOT NULL,
PRIMARY KEY (VIVIENDAID)
);

CREATE TABLE APARTAMENTO(
AMOBLADO  NUMBER(1,0) NOT NULL,
OCUPADO  NUMBER(1,0) NOT NULL,
UBICACION VARCHAR2(100) NOT NULL,
APARTAMENTOID INT,
COMUNIDADID INT NOT NULL,
RESERVAID INT,
PRIMARY KEY (APARTAMENTOID)
);

/*
CREATE TABLE CONTRATOAPTO(
INCLUYEADMIN NUMBER(1,0) NOT NULL,
INCLUYESERVPUBLICOS  NUMBER(1,0) NOT NULL,
PRECIOSERVPUBLICOS  NUMBER(1,0) NOT NULL,
CONTRATOAPTOID INT,
COMUNIDADID INT NOT NULL,
PRIMARY KEY (CONTRATOAPTOID)
);

CREATE TABLE CONTRATOVIVIENDA(
MENAJE  NUMBER(1,0) NOT NULL,
NUMEROHABITACIONES INT NOT NULL,
CONTRATOVIVIENDAID INT,
COMUNIDADID INT NOT NULL,
PRIMARY KEY (CONTRATOVIVIENDAID)
);

CREATE TABLE CONTRATOHABITACION(
ACCESOCOCINA NUMBER(1,0) NOT NULL,
BAÑOPRIVADO VARCHAR2(100) NOT NULL,
COMIDAS NUMBER(1,0) NOT NULL,
DURACION INT NOT NULL,
HABITACIONINDIVIDUAL NUMBER(1,0) NOT NULL,
PRECIOSERVICIOS INT NOT NULL,
CONTRATOHABITACIONID INT NOT NULL,
COMUNIDADID INT NOT NULL,
PRIMARY KEY (CONTRATOHABITACIONID)
);*/

/*APARTAMENTO*/
ALTER TABLE APARTAMENTO
ADD FOREIGN KEY (COMUNIDADID) REFERENCES COMUNIDAD; 

ALTER TABLE APARTAMENTO
ADD FOREIGN KEY (RESERVAID) REFERENCES RESERVA;

/*HABITACION*/
ALTER TABLE HABITACION
ADD FOREIGN KEY (COMUNIDADID) REFERENCES COMUNIDAD;

ALTER TABLE HABITACION
ADD FOREIGN KEY (HOTELERIAID) REFERENCES HOTELERIA;

ALTER TABLE HABITACION
ADD FOREIGN KEY (RESERVAID) REFERENCES RESERVA;

/*HOTELERIA*/
ALTER TABLE HOTELERIA
ADD FOREIGN KEY (COMUNIDADID) REFERENCES COMUNIDAD;

/*RESERVA*/
ALTER TABLE RESERVA
ADD FOREIGN KEY (COMUNIDADID) REFERENCES COMUNIDAD;

/*SEGURO*/
ALTER TABLE SEGURO
ADD FOREIGN KEY (RESERVAID) REFERENCES RESERVA;

/*SERVICIOS*/
ALTER TABLE SERVICIOS
ADD FOREIGN KEY (HABITACIONID) REFERENCES HABITACION;

/*VIVIENDA*/
ALTER TABLE VIVIENDA
ADD FOREIGN KEY (COMUNIDADID) REFERENCES COMUNIDAD;