/*RF1: Registrar un operador de alojamiento*/
INSERT INTO COMUNIDAD (CARNET, NOMBRE, ROL, COMUNIDADID, TIPO)
VALUES (8585858, 'Tom B. Erichsen', 'Estudiante', 520, 'OPERADOR');
INSERT INTO COMUNIDAD (CARNET, NOMBRE, ROL, COMUNIDADID, TIPO)
VALUES (8585858, 'Tomas T. Engine', 'Profesor', 521, 'OPERADOR');

/*REVISAR LOS VALORES DE OPERADOR*/
SELECT * 
FROM COMUNIDAD
WHERE TIPO = 'OPERADOR';

/*Registrar Hoteles*/
INSERT INTO HOTELERIA (NOMBRE, CAPACIDAD, DISPONIBILIDAD, REGISTROCAMARACOMERCIO, REGISTROSUPERINTENDENCIA, UBICACION, HOTELERIAID, COMUNIDADID, TIPOH)
VALUES('hotel el don', 55, 44,'si', 'si', 'Calle 9 -25', 58, 520, 'HOTEL');

/*Registrar Hostales*/
INSERT INTO HOTELERIA (NOMBRE, CAPACIDAD, DISPONIBILIDAD, REGISTROCAMARACOMERCIO, REGISTROSUPERINTENDENCIA, UBICACION, HOTELERIAID, COMUNIDADID, TIPOH)
VALUES('hostal sape', 22, 11,'si', 'si', 'Calle 89 -54', 78, 521, 'HOSTAL');

/*REVISAR HOSTELERIA*/
SELECT * FROM HOTELERIA;

/*Registrar Habitación*/
INSERT INTO HABITACION(COMPARTIDA, DESCRIPCION, OCUPADA, HABITACIONID, HOTELERIAID)
VALUES (1, 'LINDA, PEQUEÑA', 0,44, 58 );

/*REVISAR LOS VALORES DE HABITACIÓN*/
SELECT * 
FROM HABITACION;

/*RF2 Registrar propuestas de alojamientos para alohandes, EJEMPLO UNA VIVIENDA*/
INSERT INTO VIVIENDA (MENAJE, NUMEROHABITACIONES, OCUPADA, UBICACION, VIVIENDAID, COMUNIDADID)
VALUES(1, 5, 1, 'Calle 25 # 3', 45, 520);

/*REVISAR LOS VALORES DE VIVIENDA*/
SELECT * 
FROM VIVIENDA;

/*Registrar un apartamento, propuesta de alojamiento*/
INSERT INTO APARTAMENTO (AMOBLADO, OCUPADO, UBICACION, APARTAMENTOID, COMUNIDADID)
VALUES (1,0,'CALLE 1 -90', 56, 520);

/*REVISAR LOS VALORES DE APTO*/
SELECT * 
FROM APARTAMENTO;

/*REGISTRAR LAS PERSONAS HABILITADAS PARA UTILIZAR LOS SERVICIOS*/
INSERT INTO COMUNIDAD (CARNET, NOMBRE, ROL, COMUNIDADID, TIPO)
VALUES (8787895, 'Carl A. Dank', 'Padre', 344, 'CLIENTE');

/*REVISAR LOS VALORES DE CLIENTE*/
SELECT * 
FROM COMUNIDAD 
WHERE TIPO = 'CLIENTE';